name: quiz_game
description: "A new Flutter project Quiz Flow with Gamification."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  provider: ^6.1.2
  flutter_widget_from_html: ^0.15.3
  percent_indicator: ^4.2.4
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  fonts:
    - family: regular
      fonts:
        - asset: assets/fonts/ABeeZee-Regular.ttf
    - family: italic
      fonts:
        - asset: assets/fonts/ABeeZee-Italic.ttf
    - family: bold
      fonts:
        - asset: assets/fonts/Anton-Regular.ttf
